# Generated by Django 5.0.7 on 2024-08-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_role_servico_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modified', models.DateField(auto_now=True, verbose_name='Update date')),
                ('active', models.BooleanField(default=True, verbose_name='Active?')),
                ('service', models.CharField(max_length=100, verbose_name='Service')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('icon', models.CharField(choices=[('lni-rocket', 'Rocket'), ('lni-stats-up', 'Chart'), ('lni-layers', 'Design'), ('lni-users', 'Users'), ('lni-mobile', 'Mobile'), ('lni-cog', 'Gear')], max_length=12, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
