# Generated by Django 5.0.7 on 2024-08-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_service_delete_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('lni-cog', 'Gear'), ('lni-users', 'Users'), ('lni-mobile', 'Mobile'), ('lni-stats-up', 'Chart'), ('lni-rocket', 'Rocket'), ('lni-layers', 'Design')], max_length=12, verbose_name='Icon'),
        ),
    ]
