# Generated by Django 5.0.7 on 2024-08-13 15:09

import core.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('lni-stats-up', 'Chart'), ('lni-cog', 'Gear'), ('lni-layers', 'Design'), ('lni-users', 'Users'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Rocket')], max_length=12, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Image'),
        ),
    ]
