# Generated by Django 5.0.7 on 2024-08-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_service_icon_alter_team_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bio',
            field=models.TextField(default='', max_length=200, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('lni-users', 'Users'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Rocket'), ('lni-stats-up', 'Chart'), ('lni-cog', 'Gear'), ('lni-layers', 'Design')], max_length=12, verbose_name='Icon'),
        ),
    ]
