# Generated by Django 5.0.7 on 2024-10-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_team_bio_alter_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('lni-stats-up', 'Chart'), ('lni-mobile', 'Mobile'), ('lni-users', 'Users'), ('lni-cog', 'Gear'), ('lni-rocket', 'Rocket'), ('lni-layers', 'Design')], max_length=12, verbose_name='Icon'),
        ),
    ]
